### ISSUE TITLE
[server] Implement health check

### ISSUE THREAD

**Issue by thelordoftheboards** [codefoundries/UniversalRelayBoilerplate#269]
Source: [Moving a Node.js app from PaaS to Kubernetes Tutorial](https://blog.risingstack.com/moving-node-js-from-paas-to-kubernetes-tutorial/).

```js
app.get('/healthz', function (req, res, next) {  
  // check my health
  // -> return next(new Error('DB is unreachable'))
  res.sendStatus(200)
})
```

```
livenessProbe:  
    httpGet:
      # Path to probe; should be cheap, but representative of typical behavior
      path: /healthz
      port: 3000
    initialDelaySeconds: 30
    timeoutSeconds: 1
```

```
readinessProbe:  
    httpGet:
      # You can use the /healthz or something else
      path: /healthz
      port: 3000
    initialDelaySeconds: 30
    timeoutSeconds: 1
```
